#
# for huaqin misc info
#

# Huaqin add for ZQL1650-86 by liunianliang at 2018/02/09 start
obj-$(CONFIG_HQ_HARDWARE_INFO)   += hardware_info/
# Huaqin add for ZQL1650-86 by liunianliang at 2018/02/09 end

# Huaqin add for ZQL1650-1179 by liunianliang at 2018/04/20 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK)   += sim_tray/
# Huaqin add for ZQL1650-1179 by liunianliang at 2018/04/20 end
