obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_X01BD/
obj-$(CONFIG_FOCALTECH_FP)	+= focaltech_X01BD/
obj-$(CONFIG_COMMON_FP_X00TD)   += common_X00TD/
obj-$(CONFIG_CDFINGER_FP_X00TD)	+= cdfinger_X00TD/
obj-$(CONFIG_GOODIX_FP_X00TD)   += goodix_X00TD/
