#
# for huaqin hardware info
#

# Huaqin add for ZQL1650-86 by liunianliang at 2018/02/09 start
obj-$(CONFIG_HQ_HARDWARE_INFO) += hardwareInfo.o
# Huaqin add for ZQL1650-86 by liunianliang at 2018/02/09 end
