#
# for huaqin sim tray status check
#

# Huaqin add for ZQL1650-1179 by liunianliang at 2018/04/20 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK) += sim_tray.o
# Huaqin add for ZQL1650-1179 by liunianliang at 2018/04/20 end
